name: CI - Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  ci-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r etl/requirements.txt
          pip install pytest sqlfluff gitleaks

      # ---------- Code Quality ----------
      - name: Run PyTest
        run: pytest tests/

      - name: SQLFluff Lint
        run: sqlfluff lint etl/ --dialect redshift

      - name: Run Ruff (lint & fix check)
        run: ruff check .

      # ---------- Security ----------
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --no-banner --redact

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: "python:3.12-slim" # placeholder until ETL image is built
          format: "table"
          exit-code: "0" # report only, don’t fail the PR
