name: CD - ETL & Airflow Deployment

on:
  push:
    branches:
      - main
    paths:
      - "etl/**"
      - "dags/**"
      - "requirements*.txt"
      - ".github/workflows/etl.yml"

jobs:
  etl-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  # needed for OIDC → AWS

    env:
      AWS_REGION: eu-west-2
      AWS_ACCOUNT_ID: 235562991700
      ECR_REPO: urban-climate-etl
      IMAGE_TAG: latest
      DAG_BUCKET: urban-climate-airflow-dags

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::235562991700:role/urban-climate-github-role
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-actions-etl

      # --- Docker Build & Push ---
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
            | docker login --username AWS --password-stdin \
              $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build Docker image
        run: |
          if [ -f "./etl/Dockerfile" ]; then
            echo "Building from ./etl/Dockerfile"
            docker build -t $ECR_REPO:$IMAGE_TAG ./etl
          elif [ -f "./Dockerfile" ]; then
            echo "Building from root ./Dockerfile"
            docker build -t $ECR_REPO:$IMAGE_TAG .
          else
            echo "ERROR: No Dockerfile found (expected ./etl/Dockerfile or ./Dockerfile)"
            exit 1
          fi

      - name: Tag & Push image to ECR
        run: |
          docker tag $ECR_REPO:$IMAGE_TAG \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

      # --- Ensure Airflow DAG bucket exists ---
      - name: Ensure Airflow DAG bucket exists
        run: |
          if aws s3 ls "s3://$DAG_BUCKET" 2>&1 | grep -q 'NoSuchBucket'; then
            echo "Bucket does not exist, creating..."
            aws s3api create-bucket \
              --bucket $DAG_BUCKET \
              --region $AWS_REGION \
              --create-bucket-configuration LocationConstraint=$AWS_REGION
          else
            echo "Bucket already exists, continuing..."
          fi

      # --- Airflow DAG Deployment ---
      - name: Sync Airflow DAGs to S3
        run: |
          aws s3 sync dags/ s3://$DAG_BUCKET/ \
            --delete --exact-timestamps

      # --- Trigger Staging Pipeline Run ---
      - name: Trigger DAG in Airflow
        run: |
          echo "Placeholder: Trigger Airflow DAG here"
          echo "airflow dags trigger urban_climate_pipeline --conf '{\"env\": \"staging\"}'"
