name: CD - Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"   # only trigger when infra changes

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # required for OIDC
      contents: read    # needed to checkout repo

    env:
      AWS_REGION: eu-west-2

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::235562991700:role/urban-climate-github-role
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-actions-terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5 # (pin a version for consistency)

      - name: Terraform Init
        run: terraform -chdir=infra init -input=false -upgrade

      - name: Terraform Validate
        run: terraform -chdir=infra validate

      - name: Terraform Plan
        run: terraform -chdir=infra plan -input=false -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=infra apply -auto-approve -input=false tfplan
