name: Daily Data Ingestion

on:
  push:
    branches:
      - main
      - workshop-branch   # include this if you want runs on this branch
  schedule:
    - cron: "0 6 * * *"   # Run daily at 06:00 UTC
  workflow_dispatch:       # Manual trigger

jobs:
  security-checks:
    name: Security Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install security tools
        run: |
          pip install pip-audit
          pip install checkov
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.18.0/gitleaks_8.18.0_linux_x64.tar.gz | tar -xz -C /usr/local/bin

      - name: Run pip-audit (Python dependencies)
        run: pip-audit

      - name: Run Checkov (Terraform security scan)
        run: checkov -d infra/

      - name: Run Gitleaks (secret scanning)
        run: gitleaks detect --source . --no-git --verbose

  ingestion:
    name: Ingestion Jobs
    runs-on: ubuntu-latest
    needs: security-checks
    env:
      AWS_REGION: eu-west-2
      S3_BUCKET_NAME: ${{ secrets.RAW_BUCKET }}   # set in GitHub secrets
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r ingestion/requirements.txt

      - name: Run Weather Ingestion
        run: python ingestion/ingest_weather.py

      - name: Run Geospatial Ingestion
        run: python ingestion/ingest_geospatial.py

      - name: Run Demographics Ingestion
        run: python ingestion/ingest_demographics.py
