name: Daily Data Ingestion

on:
  push:
    branches:
      - main
      - workshop-branch   # also run for workshop branch
  schedule:
    - cron: "0 6 * * *"   # Run daily at 06:00 UTC
  workflow_dispatch:       # Manual trigger

jobs:
  security-checks:
    name: Security Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install security tools
        run: |
          pip install pip-audit checkov
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.28.0/gitleaks_8.28.0_linux_x64.tar.gz \
            | tar -xz -C /usr/local/bin

      - name: Run pip-audit (non-blocking)
        run: |
          echo ">>> Running pip-audit (non-blocking)..."
          pip-audit || echo "pip-audit found vulnerabilities but continuing pipeline"

      - name: Run Checkov (Terraform security scan)
        run: |
          echo ">>> Running Checkov..."
          checkov -d infra/ || echo "Checkov found issues but continuing"

      - name: Run Gitleaks (secret scanning)
        run: |
          echo ">>> Running Gitleaks..."
          gitleaks detect --source . --no-git --verbose || echo "Gitleaks found issues but continuing"

  ingestion:
    name: Ingestion Jobs
    runs-on: ubuntu-latest
    needs: security-checks
    env:
      AWS_REGION: eu-west-2
      S3_BUCKET_NAME: ${{ secrets.RAW_BUCKET }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r ingestion/requirements.txt

      - name: Run Weather Ingestion
        run: python ingestion/ingest_weather.py

      - name: Run Geospatial Ingestion
        run: python ingestion/ingest_geospatial.py

      - name: Run Demographics Ingestion
        run: python ingestion/ingest_demographics.py
